segfault fix

diff --git a/tester/unit_tests b/tester/unit_tests
--- a/tester/unit_tests
+++ b/tester/unit_tests
@@ -1,9 +1,21 @@
-for i in `seq 1 100`
+sum=0
+a=2
+n=100
+
+for i in `seq 1 $n`
 do
-    result=$(ARG=`ruby -e "puts (0..9).to_a.shuffle.join(' ')"`; ./push_swap $ARG | ./checker $ARG)
+    arguments=`ruby -e "puts (0..$a).to_a.shuffle.join(' ')"`
+    result=$(./push_swap $arguments | ./checker $arguments)
+    wc=$(./push_swap $arguments | wc -l)
+    sum=$((sum + wc))
     if [ "$result" == "OK" ]; then
-        printf "test passed\n";
+        printf "\033[32mtest $i passed\033[0m - operation count: $wc\n";
     else
-        printf "TEST FAILED\n";
+        printf "TEST FAILED\n$arguments\n";
+        exit 1;
     fi
 done
+
+avg=$(echo $sum / $n | bc -l)
+
+printf "average: $avg\n"
